name: Deploy to Staging and Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up SSH Key for Staging
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}
          SSH_PORT: ${{ secrets.STAGING_SSH_PORT }}
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
          SSH_KEY: ${{ secrets.STAGING_SSHE_SSH_KEY }}

      - name: Deploy to Staging
        run: |
          ssh -i ${{ secrets.STAGING_SSHE_SSH_KEY }} -p ${{ secrets.STAGING_SSH_PORT }} ${{ secrets.STAGING_SSH_USER }}@${{ secrets.STAGING_SSH_HOST }} "bash /app/deploy.sh hodaka_inugai"

      - name: Set Up SSH Key for Production
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.PRODUCTION_SSH_HOST }}
          SSH_PORT: ${{ secrets.PRODUCTION_SSH_PORT }}
          SSH_USER: ${{ secrets.PRODUCTION_SSH_USER }}
          SSH_KEY: ${{ secrets.PRODUCTION_SSHE_SSH_KEY }}

      - name: Deploy to Production
        if: success()
        run: |
          ssh -i ${{ secrets.PRODUCTION_SSHE_SSH_KEY }} -p ${{ secrets.PRODUCTION_SSH_PORT }} ${{ secrets.PRODUCTION_SSH_USER }}@${{ secrets.PRODUCTION_SSH_HOST }} "bash /app/deploy.sh hodaka_inugai"
