name: Deploy to Staging and Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up SSH Key and Deploy to Staging
        run: |
          ssh-keyscan -t rsa ${{ secrets.STAGING_SSH_HOST }} >> ~/.ssh/known_hosts
          ssh -i ${{ secrets.STAGING_SSH_PRIVATE_KEY }} -p ${{ secrets.STAGING_SSH_PORT }} ${{ secrets.STAGING_SSH_USER }}@${{ secrets.STAGING_SSH_HOST }} "bash /path/to/deploy.sh"

      - name: Set Up SSH Key and Deploy to Production
        if: success()
        run: |
          ssh-keyscan -t rsa ${{ secrets.PRODUCTION_SSH_HOST }} >> ~/.ssh/known_hosts
          ssh -i ${{ secrets.PRODUCTION_SSH_PRIVATE_KEY }} -p ${{ secrets.PRODUCTION_SSH_PORT }} ${{ secrets.PRODUCTION_SSH_USER }}@${{ secrets.PRODUCTION_SSH_HOST }} "bash /path/to/deploy.sh"
